[package]
name = "kataster"
version = "0.1.0"
authors = ["Boris Boutillier <boris.boutillier@gmail.com>"]
edition = "2018"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }
#bevy = { path = "/home/boris/work/rust/forks/bevy"}
#bevy = "0.2.1"
rand = "0.7.3"
#bevy_rapier2d = { git = "https://github.com/Bobox214/bevy_rapier" , branch="rapier_configuration"}
#bevy_rapier2d = { path = "/home/boris/work/rust/forks/bevy_rapier/bevy_rapier2d" }
bevy_rapier2d = "0.3.1"
bevy_contrib_bobox = {git = "https://github.com/Bobox214/bevy_contrib_bobox", features = ["rapier2d"]}
#bevy_contrib_bobox = {path = "../bevy_contrib_bobox", features = ["rapier2d"]}


# Ensure crates reference the same versions
# or customize a sub-crate version
[patch.crates-io]
bevy= {git="https://github.com/bevyengine/bevy"}
#bevy = { path = "/home/boris/work/rust/forks/bevy"}
rapier2d = {git="https://github.com/dimforge/rapier"}
